### ISSUE TITLE
Atom failing to build

### ISSUE THREAD

**Issue by evandandrea** [snapcrafters/atom#1]
Atom is failing to build in 40c0d20:
https://gist.github.com/evandandrea/6611bb343c9948111e09c06da3b14f6b

```
sed: can't read usr/share/applications/atom.desktop: No such file or directory
```

**Comment by Ads20000** [comment]
So this is `1.18.0-beta7` or `1.19.0-beta7` (the commit is unclear, which may be why this build failed).
The released versions of Atom are:
```
channels:                      
  stable:    1.19.2       (20) 180MB classic
  candidate: 1.19.2       (20) 180MB classic
  beta:      1.20.0-beta3 (22) 180MB classic
  edge:      1.20.0-beta3 (22) 180MB classic
```
So I think this can be closed. `1.20.0-beta3` is the latest version in the yaml and is building fine.

(I can't close this myself for some reason, maybe only Owners can close?)

**Comment by Ads20000** [comment]
@popey can you close this please? (or @evandandrea since you're an Owner too lol!)
