### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/atom#10]
Atom lacks an icon in the Unity Dash (has a question mark) and has the generic Electron icon in the Launcher.

```
$ snap list
atom                  1.20.0              36    snapcrafters  classic
core                  16-2.27.6           2898  canonical     core
$ snap version
snap    2.27.6
snapd   2.27.6
series  16
ubuntu  17.04
kernel  4.10.0-35-generic
```

**Comment by popey** [comment]
I see an Atom icon here, both on 16.04 and 17.10. Is this still an issue?

**Comment by Ads20000** [comment]
I think I might have actually confused the Atom and Electron icons :P
