### ISSUE TITLE
Atom can't use programs such as pylint, pycodestyle etc.

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snapcrafters/atom#13]
1. install linter plugins: `linter-pylint python-indent linter-pycodestyle`
2. install linters: ` sudo apt install python3-pycodestyle pylint3`
3. Open python file and press "save".

You get an error message saying that atom can't find pylint.

![image](https://user-images.githubusercontent.com/1492981/31279916-02ab13fa-aaab-11e7-9741-3945b3f2420c.png)

This makes the snap pretty much useless..

**Comment by merlijn-sebrechts** [comment]
I'm dumb, my bad.

**Comment by nirefter2002** [comment]
I have the same problem and I can't fix it. how did you fix it?

**Comment by merlijn-sebrechts** [comment]
@nirefter2002 

It was searching for `pylint2` while I installed `pylint3`. Install both `pylint2` and `pylint3` to solve the issue.

Explanation: Atom is a classic snap so it has full access to all the programs on your system. If it doesn't work, it's not caused by the snap, it's caused by something else.
