### ISSUE TITLE
Error loading libsystemd on Ubuntu 14.04

### ISSUE THREAD

**Issue by phirsch** [snapcrafters/atom#18]
Trying to start atom on Ubuntu 14.04 results in an error:

`/snap/atom/53/usr/share/atom/atom: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory`

This seems to be caused by `libdbus` depending on `libsystemd.so.0` which is not part of the `core` snap - and thus AFAIK should not be a dependency:

```
$ ldd /snap/atom/53/lib/x86_64-linux-gnu/libdbus-1.so.3
/snap/atom/53/lib/x86_64-linux-gnu/libdbus-1.so.3:
	[...]
	libsystemd.so.0 => not found
        [...]
```

**Comment by popey** [comment]
Confirmed in a clean 14.04 VM here. We'll take a look. Thanks!

**Comment by popey** [comment]
I've reported this on our forum, so the developers can take a look.
https://forum.snapcraft.io/t/atom-fails-to-launch-on-14-0/2775

**Comment by flexiondotorg** [comment]
@phirsch Please can you test this again using the Atom 1.23.1 snap from stable.

**Comment by phirsch** [comment]
@flexiondotorg Works beautifully now. Thanks!
