### ISSUE TITLE
Can't modify libxcb.so.1.1.0

### ISSUE THREAD

**Issue by jcpny1** [snapcrafters/atom#19]
To implement the "BIG-REQUESTS' hack for Remote Access, libxcb.so.1.1.0 needs to be edited. This library is contained in the snap, so it can't be edited. Hence, the snap-installed atom will not run using windows RDP and xfce. 
$ snap run atom
Xlib:  extension "XInputExtension" missing on display ":10.0".
Xlib:  extension "XInputExtension" missing on display ":10.0".
Xlib:  extension "XInputExtension" missing on display ":10.0".
$

**Comment by flexiondotorg** [comment]
@jcpny1 Please can you test this again using the Atom 1.23.1 snap from stable.

**Comment by flexiondotorg** [comment]
@jcpny1 We believe this is fixed. Can you please confirm?
