### ISSUE TITLE
The snapped Atom process doesn't fork when launched from CLI

### ISSUE THREAD

**Issue by jocave** [snapcrafters/atom#2]
Version tested: 1.18.0 snap rev 9

snap    2.27+git316.ef41c58~ubuntu16.04.1
snapd   2.27+git316.ef41c58~ubuntu16.04.1
series  16
ubuntu  17.04
kernel  4.10.0-32-generic

I have habit of using atom by spawning it from my bash shell in the directory of the project I want to hack on e.g.
my-code$ atom .

This worked well in the deb packaged atom and I've noticed also works in the snapped vscode for comparison. However with atom from the snap I get the following output and no return of control to the shell:

my-code$ atom .
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

I'm not sure if this is something that the confinement is blocking or possibly some behaviour created by a wrapper script.

**Comment by popey** [comment]
I've posted on the forum to bring this to the snap developer's attention. https://forum.snapcraft.io/t/atom-snap-doesnt-fork/2776

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/flexiondotorg/atom-1/commit/bed9021ed1c7efbe2b14068e76484be5904e564c
