### ISSUE TITLE
Problem when clicking URIs

### ISSUE THREAD

**Issue by ghisvail** [snapcrafters/atom#23]
As reported initially in #15, clicking on a URI in Atom (for instance a change log for a plugin) does not seem to be working properly. On Ubuntu 17.10, it spawns three consecutive Mozilla crash reports a short period of time after the click.

Apparently, the issue was confirmed for other Electron based snaps such as VSCode, so it may not be specific to Atom.

A snapshot of the issue is available [here](https://forum.snapcraft.io/t/call-for-testing-atom-1-21-1/2533/4).

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/flexiondotorg/atom-1/commit/455850dfac02f611da5714e6240b6dca7f67d2af
