### ISSUE TITLE
apm segfaults

### ISSUE THREAD

**Issue by mattcode55** [snapcrafters/atom#27]
###### When trying to search for packages in Atom

![Screenshot](https://i.imgur.com/7WR3xta.png)

###### When running `apm` manually

    $ apm
    /snap/atom/109/usr/bin/apm: line 63:  8312 Segmentation fault      (core dumped) "$binDir/$nodeBin" "$cliPath" "$@

**Comment by wandrewkeech** [comment]
Just encountered the same problem, for `atom 1.23.1 (109)`

**Comment by evanp** [comment]
Ditto here

**Comment by LanceGundersen** [comment]
Same here.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/atom/commit/78b5f36dabb11c34fa4199cb26c3cfd0d5a0baa5 and Atom 1.23.2 is released to the stable channel.
