### ISSUE TITLE
Add Atom 1.28 & 1.29 beta

### ISSUE THREAD

**Issue by ArekSredzki** [snapcrafters/atom#34]
Atom 1.28 released & 1.29 beta available: http://blog.atom.io/2018/06/21/atom-1-28.html

Is there any way to make these both available through the snap?

Thanks!

**Comment by shemgp** [comment]
Waiting for 1.28 too.

**Comment by popey** [comment]
Apologies for the delay, we're on it.

**Comment by ArekSredzki** [comment]
Thanks @popey The new edge 1.28.0 (163) artifact is working well for me thus far. much appreciated

**Comment by popey** [comment]
I don't understand how rev 163 can work for you, it's broken here, and needs more work. Are you sure you're running 163? How are you launching it?

**Comment by ArekSredzki** [comment]
Huh, must be magic!
I've tried launching it through both the CLI (`atom`) & launcher.

I'm on 16.04 with all packages up to date

**Comment by ArekSredzki** [comment]
167 works too :+1:

**Comment by popey** [comment]
Yup, 167 is the "good" one :) Thanks!
