### ISSUE TITLE
Atom won't allow opening of files from file manager

### ISSUE THREAD

**Issue by oluwatbi** [snapcrafters/atom#36]
When I try to open a project folder or file in atom, I usually don't see anything.
![screenshot from 2018-09-10 00-04-20](https://user-images.githubusercontent.com/34950749/45269873-280b0780-b48d-11e8-8764-3ca361f309bb.png)

The folders and files failed to be visible

**Comment by popey** [comment]
@oluwatbi Thanks for the report! What do I need to do to reproduce this? 
Your desktop theme is awesome by the way, which one is it? :)

**Comment by ricsdeol** [comment]
I have the same problem with opening files too, the open file / folder screen is very strange.
![image](https://user-images.githubusercontent.com/719970/47720035-b6993b00-dc2b-11e8-8ae3-78809de51e34.png)
version: 
snap-id:      Lf1MF6tizzusVuA6l13ETyH5VDXxwA0D
tracking:     stable
refresh-date: 6 days ago, at 09:48 -03
channels:                       
  stable:    1.32.0 (204) 186MB classic
Ubuntu 18.04

**Comment by oluwatbi** [comment]
@popey 
It was customized.

But I think I figured that out and I am using VS code along side.

**Comment by flexiondotorg** [comment]
Fixed via #47
