### ISSUE TITLE
Update to atom 1.31.1

### ISSUE THREAD

**Issue by alvarogzp** [snapcrafters/atom#38]
Hello! Could you please update and publish version 1.31.1 to https://snapcraft.io/atom to fix https://github.com/atom/atom/issues/18118? Thanks!

Atom releases: https://atom.io/releases

**Comment by popey** [comment]
Thanks for the issue @alvarogzp - I've triggered a [build](https://launchpad.net/~build.snapcraft.io/+snap/a327af41d53ecba7cdcf391f6b95c0cf-xenial) and will test and publish shortly.

**Comment by popey** [comment]
This has now been tested and released to the stable channel. Thanks again @alvarogzp

**Comment by alvarogzp** [comment]
Thank you @popey for doing it so quickly!
