### ISSUE TITLE
Open dialog system resources missing

### ISSUE THREAD

**Issue by khaeru** [snapcrafters/atom#41]
I'm running stock Ubuntu 18.04. When using the Atom snap, I use the system "open file" dialog (Ctrl+O).

In this dialog, all the icons show as missing; see the screenshot.
![screenshot from 2018-11-09 15-38-07](https://user-images.githubusercontent.com/1634164/48268741-2088c000-e436-11e8-8634-d1bd968597b3.png)

**Comment by flexiondotorg** [comment]
Fixed via #47
