### ISSUE TITLE
Atom icon looks like gone

### ISSUE THREAD

**Issue by brunobord** [snapcrafters/atom#49]
Apparently the main atom icon looks gone after the latest update, which happened on 2019-02-20, from 1.34.0 (rev 212) to 1.34.0 (rev 214).

Here it is when I'm searching in the available applications:
![atom-search](https://user-images.githubusercontent.com/25185/53228147-a0066c00-3680-11e9-99a2-3442eb35c4ff.png)

Here it is when loaded in the application sidebar:
![atom-sidebar](https://user-images.githubusercontent.com/25185/53228148-a0066c00-3680-11e9-9246-c84e1c3b4f54.png)

----

```
$ snap info
snap version
snap    2.37.2
snapd   2.37.2
series  16
ubuntu  18.04
kernel  4.15.0-45-generic
```

**Comment by sherif7810** [comment]
In Ubuntu 18.10,
![screenshot](https://user-images.githubusercontent.com/37023248/53229431-d944d900-368c-11e9-8779-017eb6b42191.png)

**Comment by gwvr** [comment]
Icon has also gone on AWOL on Debian 9 (Cinnamon).

**Comment by popey** [comment]
Thanks for the issue. We're looking into it. Oddly the icon is still in the package, and the desktop file appears to be modified correctly, but the result isn't working how it was.

**Comment by brunobord** [comment]
Maybe it's an access issue? ``chmod``?

**Comment by popey** [comment]
Sorry about this. Revision 221 in the stable channel has a fixed icon. Just `snap refresh` to get it.

**Comment by brunobord** [comment]
Confirming it's back. Thank you for the fix!
