### ISSUE TITLE
Release Atom 1.21 beta

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/atom#8]
Would be nice to [support Atom IDE by releasing 1.21 beta](http://www.omgubuntu.co.uk/2017/09/github-announce-atom-ide) - probably by just patching the `snapcraft.yaml` to build 1.21 beta, send to `edge`, test, release that to `beta`, then we probably should patch `snapcraft.yaml` again to build from `master` to `edge`.

This suggestion is inspired by the process [set out here](https://github.com/snapcrafters/offlineimap/issues/1#issuecomment-328801059), we maybe should hold off `master` builds for the time being - until the build service supports daily builds.

**Comment by ghisvail** [comment]
Atom 1.21 is now released. Could you update the snap package please?
