### ISSUE TITLE
Atom doesnt show up in the menus after install

### ISSUE THREAD

**Issue by gntech** [snapcrafters/atom#9]
I have installed atom as a snap package on Ubuntu 17.10 beta. After the install has finished it doesnt show up in the menus afterward. I am also unable to start via the terminal as well.

See also: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1718590

**Comment by Ads20000** [comment]
I don't have this bug. Could you post the output of `snap info atom` (or the `atom` and `core` lines of `snap list`) and `snap version` please? Here's mine (which I don't get this bug on):

```
$ snap list
atom                  1.20.0              36    snapcrafters  classic
core                  16-2.27.6           2898  canonical     core
$ snap version
snap    2.27.6
snapd   2.27.6
series  16
ubuntu  17.04
kernel  4.10.0-35-generic
```

**Comment by gntech** [comment]
Here is the output from those command.

```
$ snap info atom                                                      18:52:36
name:      atom
summary:   "A hackable text editor for the 21st Century."
publisher: snapcrafters
contact:   snappy-canonical-storeaccount@canonical.com
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.
  
snap-id: Lf1MF6tizzusVuA6l13ETyH5VDXxwA0D
commands:
  - atom
tracking:    stable
installed:   1.20.0 (36) 180MB classic
refreshed:   2017-09-15 13:32:32 +0200 CEST
channels:                
  stable:    1.20.0 (36) 180MB classic
  candidate: 1.20.0 (36) 180MB classic
  beta:      1.20.0 (36) 180MB classic
  edge:      1.20.0 (36) 180MB classic

$ snap list                                                           18:52:40
Name  Version    Rev   Developer     Notes
atom  1.20.0     36    snapcrafters  classic
core  16-2.27.6  2898  canonical     core

$ snap version                                                        18:52:42
snap    2.27.6+17.10
snapd   2.27.6+17.10
series  16
ubuntu  17.10
kernel  4.13.0-11-generic

```

**Comment by gntech** [comment]
I remember now that when I first installed the snap I already had the .deb-version of atom installed. Could this have some effect on the bug?
I have uninstalled the deb and reinstalled the snap package multiple times after that but with no change.

**Comment by popey** [comment]
I have tested here and atom shows up under 16.04 and 17.10 menus. Is this still a problem?

**Comment by gntech** [comment]
According to https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1718590/comments/4 it is a known issue when running snaps from the wayland session. So perhaps this issue should be closed as it is not Atom snap specific. I am personally unable to test this again right now since I dont run anything on wayland right now.

**Comment by popey** [comment]
Thanks for the prompt reply. I'm on snapd 2.28 where it's apparently fixed, and I'm on wayland, and not seeing the issue. So yeah, I'm gonna close it now.
